title: Tiny Llama
email: support@insightreactions.com
description: >- # this means to ignore newlines until "baseurl:"
  Discover Tiny Llama, the open-source software solution that makes advanced AI accessible and affordable. 
  Learn how it empowers users with seamless image generation and intelligent conversations from the comfort of your own home.
theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
repository: InsightReactions/tinyllama.insightreactions.github.io
url: "https://tinyllama.insightreactions.com" # the base hostname & protocol for your site, e.g. http://example.com
title_only_logo: false
logo: "logo_render_tinyllama.png"
favicon_ico: "favicon.ico"
heading_anchors: true
color_scheme: dark
aux_links:
  "Store":
    - "//insightreactions.com/store"
  "GitHub":
    - "//github.com/insightreactions/tinyllama"
  "Company":
    - "//insightreactions.com/about"
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: yellow
# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
